/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AddClientLazyImport = createFileRoute('/addClient')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AddClientLazyRoute = AddClientLazyImport.update({
  path: '/addClient',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/addClient.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/addClient': {
      id: '/addClient'
      path: '/addClient'
      fullPath: '/addClient'
      preLoaderRoute: typeof AddClientLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AddClientLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addClient"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/addClient": {
      "filePath": "addClient.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
